 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.circuitb.ui;

import com.circuitb.database.EmployeeDatabase;
import com.circuitb.model.Employee;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.ComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kazybekkhairulla
 */
public class EmployeeAppp extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeAppp
     */
    
    
    public EmployeeAppp() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        bg_role = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tf_fname = new javax.swing.JTextField();
        tf_lname = new javax.swing.JTextField();
        js_salary = new javax.swing.JSpinner();
        lbl_fname = new javax.swing.JLabel();
        lbl_lname = new javax.swing.JLabel();
        jrb_executive = new javax.swing.JRadioButton();
        tf_age = new javax.swing.JTextField();
        lbl_age = new javax.swing.JLabel();
        jcb_roles = new javax.swing.JComboBox<>();
        lbl_salary = new javax.swing.JLabel();
        lbl_role = new javax.swing.JLabel();
        jrb_management = new javax.swing.JRadioButton();
        jrb_technical = new javax.swing.JRadioButton();
        btn_save = new javax.swing.JButton();
        tf_email = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_file = new javax.swing.JMenu();
        jm_new = new javax.swing.JMenu();
        jmi_new_record = new javax.swing.JMenuItem();
        jmi_new_query = new javax.swing.JMenuItem();
        jmi_new_report = new javax.swing.JMenuItem();
        jm_open = new javax.swing.JMenu();
        jmi_open_record = new javax.swing.JMenuItem();
        jmi_open_query = new javax.swing.JMenuItem();
        jmi_open_report = new javax.swing.JMenuItem();
        jmi_close = new javax.swing.JMenuItem();
        jmi_save = new javax.swing.JMenuItem();
        jmi_save_as = new javax.swing.JMenuItem();
        jm_import = new javax.swing.JMenu();
        jmi_import_csv = new javax.swing.JMenuItem();
        jmi_import_excel = new javax.swing.JMenuItem();
        jm_export = new javax.swing.JMenu();
        jmi_export_csv = new javax.swing.JMenuItem();
        jmi_export = new javax.swing.JMenuItem();
        jmi_page_setup = new javax.swing.JMenuItem();
        jm_edit = new javax.swing.JMenu();
        jmi_undo = new javax.swing.JMenuItem();
        jmi_redo = new javax.swing.JMenuItem();
        jmi_cut = new javax.swing.JMenuItem();
        jmi_copy = new javax.swing.JMenuItem();
        jmi_paste = new javax.swing.JMenuItem();
        jmi_delete = new javax.swing.JMenuItem();
        jmi_select_all = new javax.swing.JMenuItem();
        jmi_find = new javax.swing.JMenuItem();
        jmi_replace = new javax.swing.JMenuItem();
        jm_view = new javax.swing.JMenu();
        jmi_data_view = new javax.swing.JMenuItem();
        jmi_design_view = new javax.swing.JMenuItem();
        jmi_sql_view = new javax.swing.JMenuItem();
        jm_insert = new javax.swing.JMenu();
        jmi_row = new javax.swing.JMenuItem();
        jmi_column = new javax.swing.JMenuItem();
        jmi_object = new javax.swing.JMenuItem();
        jmi_image = new javax.swing.JMenuItem();
        jm_tools = new javax.swing.JMenu();
        jmi_relationships = new javax.swing.JMenuItem();
        jmi_sql_builder = new javax.swing.JMenuItem();
        jmi_backup = new javax.swing.JMenuItem();
        jm_security = new javax.swing.JMenu();
        jmi_user_accounts = new javax.swing.JMenuItem();
        jmi_permissions = new javax.swing.JMenuItem();
        jm_records = new javax.swing.JMenu();
        jmi_data_entry_mode = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmi_next_record = new javax.swing.JMenuItem();
        jmi_previous_record = new javax.swing.JMenuItem();
        jmi_first_record = new javax.swing.JMenuItem();
        jmi_last_record = new javax.swing.JMenuItem();
        jm_sort = new javax.swing.JMenu();
        jmi_ascending = new javax.swing.JMenuItem();
        jmi_descending = new javax.swing.JMenuItem();
        jmi_filter = new javax.swing.JMenuItem();
        jmi_refresh_data = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Emp id", "First Name", "Last Name", "Age", "Salary", "Email", "Phone", "Role", "Department", "Status", "branchID", "superID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTable1ComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        js_salary.setModel(new javax.swing.SpinnerNumberModel(5000, 5000, 100000, 5000));

        lbl_fname.setText("First Name");

        lbl_lname.setText("Last Name");

        bg_role.add(jrb_executive);
        jrb_executive.setText("Executive");
        jrb_executive.setToolTipText("");
        jrb_executive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_executiveActionPerformed(evt);
            }
        });

        lbl_age.setText("Age");

        jcb_roles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbl_salary.setText("Salary");

        lbl_role.setText("Role");

        bg_role.add(jrb_management);
        jrb_management.setText("Management");
        jrb_management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_managementActionPerformed(evt);
            }
        });

        bg_role.add(jrb_technical);
        jrb_technical.setText("Technical");
        jrb_technical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_technicalActionPerformed(evt);
            }
        });

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        tf_email.setForeground(new java.awt.Color(102, 102, 102));
        tf_email.setText("example@mail.ru");
        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });

        lbl_email.setText("Email");

        jLabel1.setText("Phone Number");

        jm_file.setText("File");

        jm_new.setText("New");

        jmi_new_record.setText("New");
        jmi_new_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_new_recordActionPerformed(evt);
            }
        });
        jm_new.add(jmi_new_record);

        jmi_new_query.setText("New Query");
        jm_new.add(jmi_new_query);

        jmi_new_report.setText("New Report");
        jm_new.add(jmi_new_report);

        jm_file.add(jm_new);

        jm_open.setText("Open");

        jmi_open_record.setText("Open Record");
        jmi_open_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_open_recordActionPerformed(evt);
            }
        });
        jm_open.add(jmi_open_record);

        jmi_open_query.setText("Open Query");
        jm_open.add(jmi_open_query);

        jmi_open_report.setText("Open Report");
        jm_open.add(jmi_open_report);

        jm_file.add(jm_open);

        jmi_close.setText("Close");
        jm_file.add(jmi_close);

        jmi_save.setText("Save");
        jmi_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_saveActionPerformed(evt);
            }
        });
        jm_file.add(jmi_save);

        jmi_save_as.setText("Save As");
        jmi_save_as.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_save_asActionPerformed(evt);
            }
        });
        jm_file.add(jmi_save_as);

        jm_import.setText("Import");

        jmi_import_csv.setText("Import CSV");
        jm_import.add(jmi_import_csv);

        jmi_import_excel.setText("lmport Excel");
        jm_import.add(jmi_import_excel);

        jm_file.add(jm_import);

        jm_export.setText("Export");

        jmi_export_csv.setText("Export CSV");
        jm_export.add(jmi_export_csv);

        jmi_export.setText("Export Excel");
        jm_export.add(jmi_export);

        jm_file.add(jm_export);

        jmi_page_setup.setText("Page Setup");
        jm_file.add(jmi_page_setup);

        jMenuBar1.add(jm_file);

        jm_edit.setText("Edit");

        jmi_undo.setText("Undo");
        jmi_undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_undoActionPerformed(evt);
            }
        });
        jm_edit.add(jmi_undo);

        jmi_redo.setText("Redo");
        jmi_redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_redoActionPerformed(evt);
            }
        });
        jm_edit.add(jmi_redo);

        jmi_cut.setText("Cut");
        jmi_cut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_cutActionPerformed(evt);
            }
        });
        jm_edit.add(jmi_cut);

        jmi_copy.setText("Copy");
        jmi_copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_copyActionPerformed(evt);
            }
        });
        jm_edit.add(jmi_copy);

        jmi_paste.setText("Paste");
        jm_edit.add(jmi_paste);

        jmi_delete.setText("Delete");
        jmi_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_deleteActionPerformed(evt);
            }
        });
        jm_edit.add(jmi_delete);

        jmi_select_all.setText("Select All");
        jm_edit.add(jmi_select_all);

        jmi_find.setText("Find");
        jm_edit.add(jmi_find);

        jmi_replace.setText("Replace");
        jm_edit.add(jmi_replace);

        jMenuBar1.add(jm_edit);

        jm_view.setText("View");

        jmi_data_view.setText("Data View");
        jm_view.add(jmi_data_view);

        jmi_design_view.setText("Design View");
        jmi_design_view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_design_viewActionPerformed(evt);
            }
        });
        jm_view.add(jmi_design_view);

        jmi_sql_view.setText("SQL View");
        jm_view.add(jmi_sql_view);

        jMenuBar1.add(jm_view);

        jm_insert.setText("Insert");

        jmi_row.setText("Row");
        jmi_row.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_rowActionPerformed(evt);
            }
        });
        jm_insert.add(jmi_row);

        jmi_column.setText("Column");
        jm_insert.add(jmi_column);

        jmi_object.setText("Object");
        jm_insert.add(jmi_object);

        jmi_image.setText("Image");
        jm_insert.add(jmi_image);

        jMenuBar1.add(jm_insert);

        jm_tools.setText("Tools");

        jmi_relationships.setText("Relationships");
        jm_tools.add(jmi_relationships);

        jmi_sql_builder.setText("SQL Builder");
        jmi_sql_builder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_sql_builderActionPerformed(evt);
            }
        });
        jm_tools.add(jmi_sql_builder);

        jmi_backup.setText("Backup");
        jm_tools.add(jmi_backup);

        jm_security.setText("Security");

        jmi_user_accounts.setText("User Accounts");
        jm_security.add(jmi_user_accounts);

        jmi_permissions.setText("Permissions");
        jm_security.add(jmi_permissions);

        jm_tools.add(jm_security);

        jMenuBar1.add(jm_tools);

        jm_records.setText("Records");

        jmi_data_entry_mode.setText("Data Entry Mode");
        jm_records.add(jmi_data_entry_mode);

        jMenu2.setText("Go to");

        jmi_next_record.setText("Next Record");
        jMenu2.add(jmi_next_record);

        jmi_previous_record.setText("Previous Record");
        jMenu2.add(jmi_previous_record);

        jmi_first_record.setText("First Record");
        jmi_first_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_first_recordActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_first_record);

        jmi_last_record.setText("Last Record");
        jMenu2.add(jmi_last_record);

        jm_records.add(jMenu2);

        jm_sort.setText("Sort");

        jmi_ascending.setText("Ascending");
        jm_sort.add(jmi_ascending);

        jmi_descending.setText("Descending");
        jmi_descending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_descendingActionPerformed(evt);
            }
        });
        jm_sort.add(jmi_descending);

        jm_records.add(jm_sort);

        jmi_filter.setText("Filter");
        jm_records.add(jmi_filter);

        jmi_refresh_data.setText("Refresh Data");
        jm_records.add(jmi_refresh_data);

        jMenuBar1.add(jm_records);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_role)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_salary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(js_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jcb_roles, 0, 164, Short.MAX_VALUE)
                                .addComponent(jrb_technical)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_lname, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(tf_fname)
                                    .addComponent(lbl_fname)
                                    .addComponent(lbl_lname)
                                    .addComponent(tf_age, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_age))
                                .addComponent(jrb_executive)
                                .addComponent(jrb_management)
                                .addComponent(tf_email))
                            .addComponent(lbl_email)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_fname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_lname)
                        .addGap(5, 5, 5)
                        .addComponent(tf_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(lbl_age)
                        .addGap(2, 2, 2)
                        .addComponent(tf_age, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(lbl_email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_role)
                            .addComponent(js_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_salary))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_executive)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrb_management)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_technical)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcb_roles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_save)
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(169, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_save_asActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_save_asActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_save_asActionPerformed

    private void jmi_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_saveActionPerformed

    private void jmi_new_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_new_recordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_new_recordActionPerformed

    private void jmi_undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_undoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_undoActionPerformed

    private void jmi_redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_redoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_redoActionPerformed

    private void jmi_cutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_cutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_cutActionPerformed

    private void jmi_copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_copyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_copyActionPerformed

    private void jmi_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_deleteActionPerformed

    private void jmi_open_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_open_recordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_open_recordActionPerformed

    private void jmi_design_viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_design_viewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_design_viewActionPerformed

    private void jmi_rowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_rowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_rowActionPerformed

    private void jmi_sql_builderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_sql_builderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_sql_builderActionPerformed

    private void jmi_first_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_first_recordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_first_recordActionPerformed

    private void jmi_descendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_descendingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_descendingActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        
        
        String role = (String) jcb_roles.getSelectedItem();
        int age = Integer.parseInt(tf_age.getText());
        String first_name = (String) tf_fname.getText();
        String last_name = (String) tf_lname.getText();
        String email = (String) tf_email.getText();
        int salary = Integer.parseInt(js_salary.getValue().toString());
        
        Random rand = new Random();
        
        EmployeeDatabase.addEmployee(new Employee(rand.nextInt(1000), first_name, last_name, email, phone, role, salary, rand.nextInt(1000), rand.nextInt(1000)));
        
        updateView();
        
        
        
        
        
        
    }//GEN-LAST:event_btn_saveActionPerformed

    private void jrb_executiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_executiveActionPerformed
        if (jrb_executive.isSelected()){
            
            jcb_roles.removeAllItems();
            jcb_roles.addItem("CEO (Chief Executive Officer)");
            jcb_roles.addItem("CFO (Chief Financial Officer)");
            jcb_roles.addItem("COO (Chief Operational Officer)");

        }
    }//GEN-LAST:event_jrb_executiveActionPerformed

    private void jrb_managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_managementActionPerformed
        if (jrb_management.isSelected()){
            
            jcb_roles.removeAllItems();
            jcb_roles.addItem("Branch Manager");
            jcb_roles.addItem("Operations Manager");
        }
    }//GEN-LAST:event_jrb_managementActionPerformed

    private void jTable1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTable1ComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTable1ComponentAdded

    private void jrb_technicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_technicalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jrb_technicalActionPerformed

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeAppp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeAppp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeAppp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeAppp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeAppp().setVisible(true);
            }
        });
    }
    public void updateView(){
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);
        List<Employee> employees = EmployeeDatabase.getEmployees();
        Object[] temp = new Object[7];
        for (int i=0; i<employees.size(); i++){
            Employee emp = employees.get(i);
            temp[0]=(emp.getEmpId());
            temp[1]=emp.getFirstName();
            temp[2]=emp.getLastName();
            temp[3]=emp.getRole();
            temp[4]=(emp.getSalary());
            temp[5]=(emp.getBranchId());
            temp[6]=(emp.getSuperId());
            tableModel.addRow(temp);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_role;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jcb_roles;
    private javax.swing.JMenu jm_edit;
    private javax.swing.JMenu jm_export;
    private javax.swing.JMenu jm_file;
    private javax.swing.JMenu jm_import;
    private javax.swing.JMenu jm_insert;
    private javax.swing.JMenu jm_new;
    private javax.swing.JMenu jm_open;
    private javax.swing.JMenu jm_records;
    private javax.swing.JMenu jm_security;
    private javax.swing.JMenu jm_sort;
    private javax.swing.JMenu jm_tools;
    private javax.swing.JMenu jm_view;
    private javax.swing.JMenuItem jmi_ascending;
    private javax.swing.JMenuItem jmi_backup;
    private javax.swing.JMenuItem jmi_close;
    private javax.swing.JMenuItem jmi_column;
    private javax.swing.JMenuItem jmi_copy;
    private javax.swing.JMenuItem jmi_cut;
    private javax.swing.JMenuItem jmi_data_entry_mode;
    private javax.swing.JMenuItem jmi_data_view;
    private javax.swing.JMenuItem jmi_delete;
    private javax.swing.JMenuItem jmi_descending;
    private javax.swing.JMenuItem jmi_design_view;
    private javax.swing.JMenuItem jmi_export;
    private javax.swing.JMenuItem jmi_export_csv;
    private javax.swing.JMenuItem jmi_filter;
    private javax.swing.JMenuItem jmi_find;
    private javax.swing.JMenuItem jmi_first_record;
    private javax.swing.JMenuItem jmi_image;
    private javax.swing.JMenuItem jmi_import_csv;
    private javax.swing.JMenuItem jmi_import_excel;
    private javax.swing.JMenuItem jmi_last_record;
    private javax.swing.JMenuItem jmi_new_query;
    private javax.swing.JMenuItem jmi_new_record;
    private javax.swing.JMenuItem jmi_new_report;
    private javax.swing.JMenuItem jmi_next_record;
    private javax.swing.JMenuItem jmi_object;
    private javax.swing.JMenuItem jmi_open_query;
    private javax.swing.JMenuItem jmi_open_record;
    private javax.swing.JMenuItem jmi_open_report;
    private javax.swing.JMenuItem jmi_page_setup;
    private javax.swing.JMenuItem jmi_paste;
    private javax.swing.JMenuItem jmi_permissions;
    private javax.swing.JMenuItem jmi_previous_record;
    private javax.swing.JMenuItem jmi_redo;
    private javax.swing.JMenuItem jmi_refresh_data;
    private javax.swing.JMenuItem jmi_relationships;
    private javax.swing.JMenuItem jmi_replace;
    private javax.swing.JMenuItem jmi_row;
    private javax.swing.JMenuItem jmi_save;
    private javax.swing.JMenuItem jmi_save_as;
    private javax.swing.JMenuItem jmi_select_all;
    private javax.swing.JMenuItem jmi_sql_builder;
    private javax.swing.JMenuItem jmi_sql_view;
    private javax.swing.JMenuItem jmi_undo;
    private javax.swing.JMenuItem jmi_user_accounts;
    private javax.swing.JRadioButton jrb_executive;
    private javax.swing.JRadioButton jrb_management;
    private javax.swing.JRadioButton jrb_technical;
    private javax.swing.JSpinner js_salary;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_fname;
    private javax.swing.JLabel lbl_lname;
    private javax.swing.JLabel lbl_role;
    private javax.swing.JLabel lbl_salary;
    private javax.swing.JTextField tf_age;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_fname;
    private javax.swing.JTextField tf_lname;
    // End of variables declaration//GEN-END:variables
}
