/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.kazcables.recordview;

import com.kazcables.util.Hashing;
import java.awt.FlowLayout;
import static java.awt.image.ImageObserver.HEIGHT;
import static java.awt.image.ImageObserver.WIDTH;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;


public class Account extends javax.swing.JPanel {

    ResultSet resultSet = null;
    Connection connection = null;
    Statement statement = null;
    
    String url = "jdbc:mysql://localhost:3306/employees";
    String user = "root";
    String password = "password";
    public Account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jb_resetPassword = new javax.swing.JButton();
        jb_changeEmail = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("ElectroBase Account");

        jb_resetPassword.setText("Reset Password");
        jb_resetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_resetPasswordActionPerformed(evt);
            }
        });

        jb_changeEmail.setText("Change Email Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jb_resetPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(jb_changeEmail)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_resetPassword)
                    .addComponent(jb_changeEmail))
                .addContainerGap(220, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jb_resetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_resetPasswordActionPerformed

        createNewPassword();
    }//GEN-LAST:event_jb_resetPasswordActionPerformed
    public void createNewPassword(){

        JDialog jd = new JDialog();
        jd.setSize(WIDTH, HEIGHT);
        JPanel jp = new JPanel();
        jp.setLayout(new FlowLayout());
        JPasswordField jpass = new JPasswordField(20);

        JButton btn = new JButton("Set Password");
        btn.addActionListener(e -> {
            updatePassword(Hashing.hashPassword(new String(jpass.getPassword())));
            jd.dispose();
            JOptionPane.showMessageDialog(null, "Password reset sucessfull!!");
        });
        JButton closebtn = new JButton("Close");
        closebtn.addActionListener(e -> {
            jd.dispose();
        });
        jp.add(jpass);
        jp.add(btn);
        jp.add(closebtn);
        jd.add(jp);
        jd.pack(); // Adjust dialog size based on contents
        jd.setLocationRelativeTo(null); // Center dialog on screen
        jd.setVisible(true);
        
    }
    public void updatePassword(String newPassword){
        // Connects to the employees database, extracts and sets the model for JTable for Employee Records
        try{
            connection = DriverManager.getConnection(url, user, password);
            String sql = "UPDATE user SET password = ? WHERE username = 'user1'";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, newPassword);
            int rowsUpdated = statement.executeUpdate();
            connection.close();
        }
        catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Connection was unsuccessful!!");
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jb_changeEmail;
    private javax.swing.JButton jb_resetPassword;
    // End of variables declaration//GEN-END:variables
}
