package com.kazcables.recordview;

import com.kazcables.model.Client;
import com.kazcables.model.Employee;
import com.kazcables.model.HierarchyLevel;
import com.kazcables.model.Organization;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public final class ClientInfo extends javax.swing.JPanel {

    private final Organization organization;
    private final ClientRecords clientRecords;
    private final Client client;

    public ClientInfo(Client client, Organization organization, ClientRecords clientrecords) {
        initComponents();
        this.organization = organization;
        this.clientRecords = clientrecords;
        this.client = client;
        displayInfo();
    }

    public void displayInfo() {
        if (client != null) {
            lbl_getName.setText(client.getName());
            lbl_getEmail.setText(client.getEmail());
            lbl_getClient_id.setText(client.getClient_id() + "");
            lbl_getAssigned_to.setText("<html><a href=''> " + client.getAssigned_to() + "</a></html>");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_getName = new javax.swing.JLabel();
        lbl_getEmail = new javax.swing.JLabel();
        lbl_getClient_id = new javax.swing.JLabel();
        lbl_getPhone = new javax.swing.JLabel();
        lbl_getAssigned_to = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lbl_fname.setText("client name");

        lbl_email.setText("Email");

        lbl_client_id.setText("client id");

        btn_remove.setText("Remove Client");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        lbl_phone.setText("Phone Number");

        lbl_assigned_to.setText("assigned to");

        lbl_getAssigned_to.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_getAssigned_toMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lbl_fname)
                        .addGap(27, 27, 27)
                        .addComponent(lbl_getName, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_remove)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_assigned_to)
                                        .addComponent(lbl_client_id)
                                        .addComponent(lbl_email))
                                    .addGap(17, 17, 17)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(lbl_getAssigned_to, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lbl_getClient_id, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_getEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_getPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_fname)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_client_id))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_getName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_getClient_id, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_assigned_to))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_getAssigned_to, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_email)
                    .addComponent(lbl_getEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_getPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btn_remove)
                        .addGap(24, 24, 24))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        if (client != null) {
            boolean removed = this.organization.removeClient(client);
            if (removed) {
                JOptionPane.showMessageDialog(null, "Successfully removed " + client.getName());
                this.clientRecords.showClients();
            } else {
                JOptionPane.showMessageDialog(null, "Client " + client.getName() + " not found, redirecting back to application...");
            }
        }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void lbl_getAssigned_toMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_getAssigned_toMouseClicked
        if (client.getAssigned_to() != null) {
            Employee salesMan = this.getOrganization().searchEmployeeByID(client.getBranch_id(), HierarchyLevel.SALES, client.getAssigned_to());
            if (salesMan != null) {
                openSalesmanInfo(salesMan);
            }
        }
    }//GEN-LAST:event_lbl_getAssigned_toMouseClicked
    public void openSalesmanInfo(Employee emp) {
        JFrame fr = new JFrame();
        SalesmanInfo info = new SalesmanInfo(emp, this.organization);
        fr.setSize(400, 400);
        fr.add(info);
        fr.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private final javax.swing.JButton btn_remove = new javax.swing.JButton();
    private javax.swing.JPanel jPanel1;
    private final javax.swing.JLabel lbl_assigned_to = new javax.swing.JLabel();
    private final javax.swing.JLabel lbl_client_id = new javax.swing.JLabel();
    private final javax.swing.JLabel lbl_email = new javax.swing.JLabel();
    private final javax.swing.JLabel lbl_fname = new javax.swing.JLabel();
    private javax.swing.JLabel lbl_getAssigned_to;
    private javax.swing.JLabel lbl_getClient_id;
    private javax.swing.JLabel lbl_getEmail;
    private javax.swing.JLabel lbl_getName;
    private javax.swing.JLabel lbl_getPhone;
    private final javax.swing.JLabel lbl_phone = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables

    public Organization getOrganization() {
        return organization;
    }

    public ClientRecords getClientRecords() {
        return clientRecords;
    }
}
