
package com.kazcables.recordview;

import com.kazcabels.model.Employee;
import com.kazcabels.model.Organization;
import java.util.Stack;
import javax.swing.JOptionPane;


public class EmployeeInfo extends javax.swing.JPanel {

    private final Organization organization;
    private final EmployeeRecords employeeRecords;
    private Stack<Employee> forward;
    private Stack<Employee> history;
    private Employee emp;
    private int currentIndex = -1;
    public EmployeeInfo(Employee emp, Organization organization, EmployeeRecords emprecords) {
        initComponents();
        this.organization = organization;
        this.employeeRecords = emprecords;
        this.forward = new Stack<>();
        this.history = new Stack<>();
        this.emp = emp;
        btn_previous.setVisible(false);
        displayInfo();
        ta_role.setWrapStyleWord(true);
        ta_role.setLineWrap(true);
        
    }
    public void displayInfo(){
        if (emp!=null){
            lbl_getFirstName.setText(emp.getName());
            lbl_getLastName.setText(emp.getLastName());
            lbl_getBirthDate.setText(emp.getBirthDate());
            lbl_getEmail.setText(emp.getEmail());
            lbl_getEmp_id.setText(emp.getEmp_Id());
            lbl_getSuper_id.setText("<html><a href=''> "+ emp.getSupervisor_id()+ "</a></html>");
            lbl_getDepartment.setText(emp.getDepartment().getName());
            String[] description = emp.getRole().getDescription().split(",");
            String formattedDescription = "";
            for (String str: description){
                formattedDescription = formattedDescription + str + "\n";
            }
            ta_role.setText(formattedDescription);
        }
    }
    public void goForward(){
        if (!forward.isEmpty()){
            history.push(emp);
            emp = forward.pop();
            displayInfo();
            currentIndex++;
        }
    }
    public void goBack(){
        if (!history.isEmpty()){
            forward.push(emp);
            emp = history.pop();
            displayInfo();
            currentIndex--;
            if (currentIndex==0){
                btn_previous.setEnabled(false);
                JOptionPane.showMessageDialog(null, currentIndex+"");
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_fname = new javax.swing.JLabel();
        lbl_getFirstName = new javax.swing.JLabel();
        lbl_lname = new javax.swing.JLabel();
        lbl_getLastName = new javax.swing.JLabel();
        lbl_birthDate = new javax.swing.JLabel();
        lbl_getBirthDate = new javax.swing.JLabel();
        lbl_getDepartment = new javax.swing.JLabel();
        lbl_department = new javax.swing.JLabel();
        lbl_getEmail = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_emp_id = new javax.swing.JLabel();
        lbl_getEmp_id = new javax.swing.JLabel();
        lbl_super_id = new javax.swing.JLabel();
        lbl_getSuper_id = new javax.swing.JLabel();
        lbl_role = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_role = new javax.swing.JTextArea();
        btn_previous = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lbl_fname.setText("First Name");

        lbl_lname.setText("Last Name");

        lbl_birthDate.setText("Birth Date");

        lbl_department.setText("Department");

        lbl_email.setText("Email");

        lbl_emp_id.setText("employee id");

        lbl_super_id.setText("supervisor id");

        lbl_getSuper_id.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_getSuper_idMouseClicked(evt);
            }
        });

        lbl_role.setText("Role Description");

        ta_role.setEditable(false);
        ta_role.setColumns(20);
        ta_role.setRows(5);
        ta_role.setMaximumSize(new java.awt.Dimension(50, 100));
        jScrollPane1.setViewportView(ta_role);

        btn_previous.setText("back");
        btn_previous.setEnabled(false);
        btn_previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_previousActionPerformed(evt);
            }
        });

        btn_remove.setText("Remove Employee");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_role)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_fname)
                                    .addComponent(lbl_lname))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_getLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_getFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(181, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_department)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_getDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_emp_id)
                                            .addComponent(lbl_super_id))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_getEmp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_getSuper_id, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_email)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbl_getEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_birthDate)
                                            .addGap(33, 33, 33)
                                            .addComponent(lbl_getBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGap(158, 158, 158))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_previous)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_previous)
                    .addComponent(btn_remove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_fname)
                            .addComponent(lbl_getFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_lname))
                    .addComponent(lbl_getLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_getEmp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_emp_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_getSuper_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_super_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_birthDate)
                    .addComponent(lbl_getBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_email)
                    .addComponent(lbl_getEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_department)
                    .addComponent(lbl_getDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(lbl_role)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_getSuper_idMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_getSuper_idMouseClicked
        // TODO add your handling code here:
        if (emp != null && emp.getSupervisor_id()!=null){
            Employee supervisor = this.organization.searchEmployeeByID(emp.getSupervisor_id());
            if (supervisor!=null){
                history.push(emp);
                emp = supervisor;
                forward.clear();
                displayInfo();
                btn_previous.setEnabled(true);
                btn_previous.setVisible(true);
            }
        }
    }//GEN-LAST:event_lbl_getSuper_idMouseClicked

    private void btn_previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_previousActionPerformed
        goBack();
        
    }//GEN-LAST:event_btn_previousActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        if (emp!=null)
        {
            boolean removed = this.organization.removeEmployee(emp.getFullName().toLowerCase());
            if (removed){
                JOptionPane.showMessageDialog(null, "Successfully removed " + emp.getFullName());
                this.employeeRecords.showEmployees();
                this.employeeRecords.getRemoved().push(emp.getEmp_Id());
            }
        }
    }//GEN-LAST:event_btn_removeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_previous;
    private javax.swing.JButton btn_remove;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_birthDate;
    private javax.swing.JLabel lbl_department;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_emp_id;
    private javax.swing.JLabel lbl_fname;
    private javax.swing.JLabel lbl_getBirthDate;
    private javax.swing.JLabel lbl_getDepartment;
    private javax.swing.JLabel lbl_getEmail;
    private javax.swing.JLabel lbl_getEmp_id;
    private javax.swing.JLabel lbl_getFirstName;
    private javax.swing.JLabel lbl_getLastName;
    private javax.swing.JLabel lbl_getSuper_id;
    private javax.swing.JLabel lbl_lname;
    private javax.swing.JLabel lbl_role;
    private javax.swing.JLabel lbl_super_id;
    private javax.swing.JTextArea ta_role;
    // End of variables declaration//GEN-END:variables
}
