package com.kazcables.recordview;

import com.kazcabels.model.BranchSupplier;
import com.kazcabels.model.Organization;
import com.kazcabels.model.Supply;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;



public final class SupplierRecords extends javax.swing.JPanel {

    
    private Organization organization;
    
    
    public SupplierRecords(Organization organization) {
        
        initComponents();
        this.organization.initSuppliers();
        showSuppliers();
        showSupplies();
        String[] searchParameter = new String[]{"by supplier name"};
        DefaultComboBoxModel model = new DefaultComboBoxModel<>(searchParameter);
        
    }
    public void addSupplierRow(String[] supplierRecord){
        DefaultTableModel model = (DefaultTableModel) supplierList.getModel();
        model.addRow(supplierRecord);
        supplierList.setModel(model);
    }
    public void addSupplyRow(String[] supply){
        DefaultTableModel model = (DefaultTableModel) supplyList.getModel();
        model.addRow(supply);
        supplyList.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        supplierList = new javax.swing.JTable();
        lbl_clientRecords1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        supplyList = new javax.swing.JTable();
        lbl_supply = new javax.swing.JLabel();
        tf_searchField = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        supplierList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(supplierList);

        lbl_clientRecords1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbl_clientRecords1.setText("Branch Supplier Records");

        supplyList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(supplyList);

        lbl_supply.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbl_supply.setText("Supplies");

        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        jLabel1.setText("Search Branch Supplier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_supply))
                    .addComponent(lbl_clientRecords1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(tf_searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_search)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbl_clientRecords1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(lbl_supply)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        
    }//GEN-LAST:event_btn_searchActionPerformed
    public void showSuppliers(){
        HashMap<String, BranchSupplier> allSuppliers = this.organization.getAllSuppliers();
        for (Map.Entry<String, BranchSupplier> entry: allSuppliers.entrySet())
        {
            String[] row = entry.getValue().getRow();
            addSupplierRow(row);
        }
    }
    public void showSupplies(){
        DefaultTableModel model = (DefaultTableModel) supplyList.getModel();
        model.setRowCount(0);
        HashMap<String, BranchSupplier> allSuppliers = this.organization.getAllSuppliers();
        if (!allSuppliers.isEmpty())
        {
            for (Map.Entry<String, BranchSupplier> entry: allSuppliers.entrySet())
            {
                BranchSupplier supplier = entry.getValue();
                Map<Integer, List<Supply>> supplies = supplier.getSuppliesToBranches();

                for (Map.Entry<Integer, List<Supply>> supplyEntry: supplies.entrySet())
                {
                    List<Supply> listSupplies = supplyEntry.getValue();
                    for (Supply supply: listSupplies)
                    {
                        String[] row = supply.getRow();
                        row[1] = supplyEntry.getKey()+"";
                        row[4] = supplier.getName();
                        addSupplyRow(row);
                    }
                }
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_clientRecords1;
    private javax.swing.JLabel lbl_supply;
    private javax.swing.JTable supplierList;
    private javax.swing.JTable supplyList;
    private javax.swing.JTextField tf_searchField;
    // End of variables declaration//GEN-END:variables
}
