/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.kazcables.forms;

import com.kazcables.util.Db;
import com.kazcables.util.Hashing;
import com.kazcables.util.Mail;
import java.awt.FlowLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.mail.MessagingException;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;



public class ForgotPassword extends javax.swing.JDialog 
{
    Connection connection = null;
    
    private String random;
    private String from = "";
    private String to = "";
    
    public ForgotPassword(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        this.setSize(500,200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_verify = new javax.swing.JLabel();
        btn_sendCode = new javax.swing.JButton();
        btn_verifyOTP = new javax.swing.JButton();
        lbl_email = new javax.swing.JLabel();
        lbl_entryOTP = new javax.swing.JLabel();
        tf_entryOTP = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        jb_close = new javax.swing.JButton();
        jb_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_verify.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N

        btn_sendCode.setText("Send OTP");
        btn_sendCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendCodeActionPerformed(evt);
            }
        });

        btn_verifyOTP.setText("Verify OTP");
        btn_verifyOTP.setEnabled(false);
        btn_verifyOTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verifyOTPActionPerformed(evt);
            }
        });

        lbl_email.setText("Email Address: ");

        lbl_entryOTP.setText("Enter OTP");
        lbl_entryOTP.setEnabled(false);

        tf_entryOTP.setToolTipText("Only digits accepted");
        tf_entryOTP.setEnabled(false);

        jb_close.setText("Close");
        jb_close.setEnabled(false);
        jb_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_closeActionPerformed(evt);
            }
        });

        jb_cancel.setText("Cancel");
        jb_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jb_cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_close))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_entryOTP)
                            .addComponent(lbl_email))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_email)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_verify)
                                    .addComponent(tf_entryOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 94, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_verifyOTP)
                            .addComponent(btn_sendCode))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_sendCode)
                            .addComponent(lbl_email)
                            .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_verifyOTP)
                            .addComponent(tf_entryOTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_entryOTP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_close)
                            .addComponent(jb_cancel))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_verify)
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendCodeActionPerformed
        emailOTP();

    }//GEN-LAST:event_btn_sendCodeActionPerformed

    private void btn_verifyOTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verifyOTPActionPerformed
        String otp = (String)tf_entryOTP.getText().trim();
        if (otp.equals(random)){
            lbl_verify.setText("Successfully verified");
            createNewPassword();
        }
    }//GEN-LAST:event_btn_verifyOTPActionPerformed

    private void jb_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_jb_closeActionPerformed

    private void jb_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jb_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ForgotPassword dialog = new ForgotPassword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void emailOTP(){
        // TODO add your handling code here:
        String email = (String)tf_email.getText();
        String regex = "^[A-Za-z0-9+_.-]+@(.+)$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(email);
        if (matcher.matches()){
            tf_entryOTP.setEnabled(true);
            lbl_entryOTP.setEnabled(true);
            btn_verifyOTP.setEnabled(true);
            this.from = email;
            this.to = email;
            generateOTP();
            try {
                Mail.SendMail(from, to, "Password Reset", random + " This is your OTP!");
            } catch (MessagingException ex) {
                Logger.getLogger(ForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void generateOTP(){
        random = "";
        Random r = new Random();
        for (int i=0; i<6; i++){
            random = random + Integer.toString(r.nextInt(10));
        }
    }
    public void createNewPassword()
    {
        this.dispose();
        JDialog jd = new JDialog(this, false);
        jd.setSize(WIDTH, HEIGHT);
        JPanel jp = new JPanel();
        jp.setLayout(new FlowLayout());
        JPasswordField jpass = new JPasswordField(20);

        JButton btn = new JButton("Set Password");
        btn.addActionListener(e -> {
            updatePassword(Hashing.hashPassword(new String(jpass.getPassword())));
            jd.dispose();
            JOptionPane.showMessageDialog(rootPane, "Password reset sucessfull!!");
        });
        JButton closebtn = new JButton("Close");
        closebtn.addActionListener(e -> {
            jd.dispose();
        });
        jp.add(jpass);
        jp.add(btn);
        jp.add(closebtn);
        jd.add(jp);
        jd.pack(); // Adjust dialog size based on contents
        jd.setLocationRelativeTo(null); // Center dialog on screen
        jd.setVisible(true);
        
    }
    public void updatePassword(String newPassword){
        // Connects to the employees database, extracts and sets the model for JTable for Employee Records
        try{
            connection = DriverManager.getConnection(Db.URL, Db.USER, Db.PASSWORD);
            String sql = "UPDATE user SET password = ? WHERE username = 'user1'";
            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setString(1, newPassword);
            int rowsUpdated = statement.executeUpdate();
            connection.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Connection was unsuccessful!!");
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sendCode;
    private javax.swing.JButton btn_verifyOTP;
    private javax.swing.JButton jb_cancel;
    private javax.swing.JButton jb_close;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_entryOTP;
    private javax.swing.JLabel lbl_verify;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_entryOTP;
    // End of variables declaration//GEN-END:variables
}
